# Generated by Django 5.1.5 on 2025-01-31 18:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer_hi",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="faq",
            name="question_hi",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
